run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - gosec
    - misspell
    - goconst
    - gocyclo
    - dupl
    - funlen
    - gocognit
    - lll

linters-settings:
  gocyclo:
    min-complexity: 15
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 15
  lll:
    line-length: 140
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - gocyclo
        - funlen
        - gocognit
        - lll
        - dupl
    - path: proto/
      linters:
        - all
  exclude:
    - "exportloopref"
    - "deadcode"
    - "structcheck"
    - "varcheck"
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 