// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/rates/rates.proto

package rates

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRatesRequest for retrieving exchange rates
type GetRatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Market pair, e.g., "usdtrub"
	Market        string `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesRequest) Reset() {
	*x = GetRatesRequest{}
	mi := &file_proto_rates_rates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesRequest) ProtoMessage() {}

func (x *GetRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rates_rates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesRequest.ProtoReflect.Descriptor instead.
func (*GetRatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_rates_rates_proto_rawDescGZIP(), []int{0}
}

func (x *GetRatesRequest) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

// GetRatesResponse contains exchange rate information
type GetRatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ask price (selling price)
	Ask string `protobuf:"bytes,1,opt,name=ask,proto3" json:"ask,omitempty"`
	// Bid price (buying price)
	Bid string `protobuf:"bytes,2,opt,name=bid,proto3" json:"bid,omitempty"`
	// Timestamp when the rate was retrieved
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Market pair
	Market        string `protobuf:"bytes,4,opt,name=market,proto3" json:"market,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesResponse) Reset() {
	*x = GetRatesResponse{}
	mi := &file_proto_rates_rates_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesResponse) ProtoMessage() {}

func (x *GetRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rates_rates_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesResponse.ProtoReflect.Descriptor instead.
func (*GetRatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_rates_rates_proto_rawDescGZIP(), []int{1}
}

func (x *GetRatesResponse) GetAsk() string {
	if x != nil {
		return x.Ask
	}
	return ""
}

func (x *GetRatesResponse) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *GetRatesResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GetRatesResponse) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

// HealthcheckRequest for health status check
type HealthcheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckRequest) Reset() {
	*x = HealthcheckRequest{}
	mi := &file_proto_rates_rates_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckRequest) ProtoMessage() {}

func (x *HealthcheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rates_rates_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckRequest.ProtoReflect.Descriptor instead.
func (*HealthcheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_rates_rates_proto_rawDescGZIP(), []int{2}
}

// HealthcheckResponse with service status
type HealthcheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service status
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Service version
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Timestamp of the check
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckResponse) Reset() {
	*x = HealthcheckResponse{}
	mi := &file_proto_rates_rates_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckResponse) ProtoMessage() {}

func (x *HealthcheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rates_rates_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckResponse.ProtoReflect.Descriptor instead.
func (*HealthcheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_rates_rates_proto_rawDescGZIP(), []int{3}
}

func (x *HealthcheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthcheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthcheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_proto_rates_rates_proto protoreflect.FileDescriptor

const file_proto_rates_rates_proto_rawDesc = "" +
	"\n" +
	"\x17proto/rates/rates.proto\x12\x05rates\x1a\x1fgoogle/protobuf/timestamp.proto\")\n" +
	"\x0fGetRatesRequest\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\"\x88\x01\n" +
	"\x10GetRatesResponse\x12\x10\n" +
	"\x03ask\x18\x01 \x01(\tR\x03ask\x12\x10\n" +
	"\x03bid\x18\x02 \x01(\tR\x03bid\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06market\x18\x04 \x01(\tR\x06market\"\x14\n" +
	"\x12HealthcheckRequest\"\x81\x01\n" +
	"\x13HealthcheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\x91\x01\n" +
	"\fRatesService\x12;\n" +
	"\bGetRates\x12\x16.rates.GetRatesRequest\x1a\x17.rates.GetRatesResponse\x12D\n" +
	"\vHealthcheck\x12\x19.rates.HealthcheckRequest\x1a\x1a.rates.HealthcheckResponseB)Z'github.com/alik/TestForWork/proto/ratesb\x06proto3"

var (
	file_proto_rates_rates_proto_rawDescOnce sync.Once
	file_proto_rates_rates_proto_rawDescData []byte
)

func file_proto_rates_rates_proto_rawDescGZIP() []byte {
	file_proto_rates_rates_proto_rawDescOnce.Do(func() {
		file_proto_rates_rates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rates_rates_proto_rawDesc), len(file_proto_rates_rates_proto_rawDesc)))
	})
	return file_proto_rates_rates_proto_rawDescData
}

var file_proto_rates_rates_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_rates_rates_proto_goTypes = []any{
	(*GetRatesRequest)(nil),       // 0: rates.GetRatesRequest
	(*GetRatesResponse)(nil),      // 1: rates.GetRatesResponse
	(*HealthcheckRequest)(nil),    // 2: rates.HealthcheckRequest
	(*HealthcheckResponse)(nil),   // 3: rates.HealthcheckResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_rates_rates_proto_depIdxs = []int32{
	4, // 0: rates.GetRatesResponse.timestamp:type_name -> google.protobuf.Timestamp
	4, // 1: rates.HealthcheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	0, // 2: rates.RatesService.GetRates:input_type -> rates.GetRatesRequest
	2, // 3: rates.RatesService.Healthcheck:input_type -> rates.HealthcheckRequest
	1, // 4: rates.RatesService.GetRates:output_type -> rates.GetRatesResponse
	3, // 5: rates.RatesService.Healthcheck:output_type -> rates.HealthcheckResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_rates_rates_proto_init() }
func file_proto_rates_rates_proto_init() {
	if File_proto_rates_rates_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rates_rates_proto_rawDesc), len(file_proto_rates_rates_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rates_rates_proto_goTypes,
		DependencyIndexes: file_proto_rates_rates_proto_depIdxs,
		MessageInfos:      file_proto_rates_rates_proto_msgTypes,
	}.Build()
	File_proto_rates_rates_proto = out.File
	file_proto_rates_rates_proto_goTypes = nil
	file_proto_rates_rates_proto_depIdxs = nil
}
